const jokeList = [
  "Aspiring Professional Pillow Fluffer",
  "Aspiring Chief Unicorn Wrangler",
  "Aspiring Pizza Taste Tester",
  "Aspiring Galactic Chocolate Consultant",
  "Aspiring Director of Emoji Interpretation",
  "Aspiring Professional Ice Cream Flavor Inventor",
  "Aspiring World Champion Paper Airplane Pilot",
  "Aspiring Chief Cat Video Curator",
  "Aspiring Professional Cloud Watcher",
  "Aspiring Captain of the Starship Snacketeria",
  "Aspiring Pajama Fashionista",
  "Aspiring Head of Sock Puppet Theatre",
  "Aspiring Professional Bubble Wrap Popper",
  "Aspiring Master of Random Facts",
  "Aspiring Expert in Microwave Culinary Arts",
  "Aspiring Space Travel Agent for Pets",
  "Aspiring Hula Hoop Spinner",
  "Aspiring Chief Cupcake Taste Tester",
  "Aspiring Captain of the S.S. Sillypants",
  "Aspiring Chief Imaginator",
  "Aspiring Grand Puzzlemaster",
  "Aspiring Head of Nonsense Engineering",
  "Aspiring Professional Bubble Gum Blower",
  "Aspiring Supreme High Fiver",
  "Aspiring Earphone Tangler",
  "Aspiring Chief Jigsaw Puzzle Solver",
  "Aspiring Director of Silly Dances",
  "Aspiring Awkward Silence Curator",
  "Aspiring Dream Architect",
  "Aspiring Ventriloquist",
  "Aspiring Word Inventor",
  "Aspiring Blanket Fort Architect",
  "Aspiring Director of Epic Water Balloon Fights",
  "Aspiring Proponent of Silly Hats",
  "Aspiring Cookie Dunker",
  "Aspiring Sock Matcher",
  "Aspiring Marshmallow Roaster",
  "Aspiring Professional Face Painter",
  "Aspiring Ice Cream Sundae Sculptor",
  "Aspiring Synchronized Spoon Clanker",
  "Aspiring Fortune Cookie Message Writer",
  "Aspiring Coffee Snob",
  "Aspiring Tic-Tac-Toe Winner",
  "Aspiring Galactic Donut",
  "Aspiring Pizza Dough Spinner",
  "Aspiring Origami Swan Folder",
  "Aspiring Cupcake Juggler",
  "Aspiring Cricket Orchestra Conductor",
  "Aspiring Robot Dog Walker",
  "Aspiring Oreo Stacker",
];

export const randomJoke = () => {
  const randomIndex = Math.floor(Math.random() * jokeList.length);
  return jokeList[randomIndex];
};
